version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    ports:
      - 5434:5432
    environment:  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd123456789
      POSTGRES_DB: postgres
    networks:
      - nestjs-networks
#DB for test case
  test-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - 5435:5432
    environment:  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd123456789
      POSTGRES_DB: postgres
    networks:
      - nestjs-networks   
networks:
  nestjs-networks:
#Create containers, networks,...from "docker compose" file:
#-d: deamon/background mode
#docker compose up -d
#docker compose up -d dev-database -d